# Generated by Django 4.2.15 on 2024-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websiteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteimage',
            name='category',
            field=models.CharField(choices=[('hero', 'Hero Image'), ('background', 'Background Image'), ('menu', 'Menu Item Image'), ('gallery', 'Gallery Image'), ('featured_dish', 'Featured Dish Image'), ('testimonial_background', 'Testimonial Background Image'), ('history_background', 'History Background Image'), ('team_member', 'Team Member Image')], max_length=25),
        ),
    ]
