# Generated by Django 4.2.15 on 2024-08-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_menupost'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupost',
            name='blurb',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='menupost',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.websiteimage'),
        ),
    ]
